songs = [
    {
        id: '00013',
        name: 'Die For You',
        path: 'audio/Joji - Die For You.mp3',
        artist: 'Joji',
        cover: 'img/banner/00013.jpg',
    },
    {
        id: '00009',
        name: 'MOT NGUOI VI EM',
        path: 'audio/mot nguoi vi em (midnight) _ WEAN.ogg',
        artist: 'WEAN',
        cover: 'img/banner/00009.jpg',
    },
    {
        id: '00012',
        name: 'Matsuri',
        path: 'audio/Fujii Kaze - Matsuri (まつり).mp3',
        artist: 'Fujii Kaze',
        cover: 'img/banner/00012.jpg',
    },
    {
        id: '00085',
        name: "telepatía",
        path: "audio/Kali Uchis _ telepatía.mp3",
        artist: 'Kali Uchis',
        cover: 'img/banner/00085.jpg',
    },
    {
        id: '00014',
        name: 'Die For You (with Ariana Grande) - Remix',
        path: 'audio/The Weeknd Ariana Grande - Die For You.mp3',
        artist: 'The Weeknd, Ariana Grande',
        cover: 'img/banner/00014.jpg',
    },
    {
        id: '00026',
        name: 'Kaerou',
        path: 'audio/Fujii Kaze - Kaerou.mp3',
        artist: 'Fujii Kaze',
        cover: 'img/banner/00026.jpg',
    },
    {
        id: '00021',
        name: 'Baby Why',
        path: 'audio/Sarah Cothran - Baby Why.mp3',
        artist: 'Sarah Cothran',
        cover: 'img/banner/00021.jpg',
    },
    {
        id: '00022',
        name: 'Chạy Ngay Đi',
        path: 'audio/CHẠY NGAY ĐI _ RUN NOW _ SƠN TÙNG M-TP.mp3',
        artist: 'Sơn Tùng M-TP, Onionn.',
        cover: 'img/banner/00022.jpg',
    },
    {
        id: '00003',
        name: 'Cắt kéo trên Lênin',
        path: 'audio/00003.m4a',
        artist: 'Low G',
        cover: 'img/banner/00003.jpg',
    },
    {
        id: '00004',
        name: 'Peaches (feat. Daniel Caesar & Giveon)',
        path: 'audio/Peaches (ft. Daniel Caesar, Giveon) _ Justin Bieber.ogg',
        artist: 'Justin Bieber, Daniel Caesar, Giveon',
        cover: 'img/banner/00004.jpg',
    },
    {
        id: '00016',
        name: 'Chìm Sâu',
        path: 'audio/Chìm Sâu - RPT MCK ( ft. Trung Trần ).mp3',
        artist: 'RPT MCK, Trung Trần',
        cover: 'img/banner/00016.jpg',
    },
    {
        id: '00006',
        name: 'Hard Feelings',
        path: 'audio/Hard Feelings _ Lorde.ogg',
        artist: 'Lorde',
        cover: 'img/banner/00006.jpg',
    },
    {
        id: '00086',
        name: 'Head In The Clouds',
        path: 'audio/joji - Head in the Clouds.mp3',
        artist: '88rising, Joji',
        cover: 'img/banner/00086.jpg',
    },
    {
        id: '00035',
        name: 'golden hour - Ruel Remix',
        path: 'audio/JVKE - golden hour (Ruel Remix) .mp3',
        artist: 'JVKE, Ruel',
        cover: 'img/banner/00035.jpg',
    },
    {
        id: '00010',
        name: 'magnolia',
        path: 'audio/00010.aac',
        artist: 'keshi',
        cover: 'img/banner/00010.jpg',
    },
    {
        id: '00027',
        name: 'YASASHISA',
        path: 'audio/Fujii Kaze - YASASHISA.mp3',
        artist: 'Fujii Kaze',
        cover: 'img/banner/00027.jpg',
    },
    {
        id: '00018',
        name: 'YOUR SMILE',
        path: 'audio/Obito ft. hnhngan live YOUR SMILE - Emma x Seachains x Obito.mp3',
        artist: 'Emma, Seachains, Obito, hnhngan',
        cover: 'img/banner/00018.jpg',
    },
    {
        id: '00061',
        name: 'Close To The Edge',
        path: 'audio/Close To The Edge by Fulton Lee.mp3',
        artist: 'Fulton Lee',
        cover: 'img/banner/00061.jpg',
    },
    {
        id: '00007',
        name: 'ガランド (Garando)',
        path: 'audio/ガランド _ NORISTRY.ogg',
        artist: 'NORISTRY',
        cover: 'img/banner/00007.jpg',
    },
    {
        id: '00023',
        name: 'CHẠY NGAY ĐI - Onionn Remixx',
        path: 'audio/CHẠY NGAY ĐI (ONIONN REMIX)_ RUN NOW (ONIONN REMIX) _ SƠN TÙNG M-TP.mp3',
        artist: 'Sơn Tùng M-TP, Onionn.',
        cover: 'img/banner/00023.jpg',
    },
    {
        id: '00024',
        name: 'Kirari',
        path: 'audio/Fujii Kaze _Kirari.mp3',
        artist: 'Fujii Kaze',
        cover: 'img/banner/00024.jpg',
    },
    {
        id: '00000',
        name: '踊り子 (Odoriko)',
        path: 'audio/踊り子 - Vaundy.mp3',
        artist: 'Vaundy',
        cover: 'img/banner/00000.jpg',
    },
    {
        id: '00019',
        name: 'Anh Đã Ổn Hơn',
        path: 'audio/Anh Đã Ổn Hơn - RPT MCK.mp3',
        artist: 'RPT MCK',
        cover: 'img/banner/00015.jpg',
    },
    {
        id: '00020',
        name: 'Forever (feat. Post Malone & Clever)',
        path: 'audio/Justin Bieber - Forever (feat. Post Malone Clever).mp3',
        artist: 'Justin Bieber, Post Malone, Clever',
        cover: 'img/banner/00020.jpg',
    },
    {
        id: '00001',
        name: 'Không Thích',
        path: 'audio/Không Thích _ Low G.mp3',
        artist: 'Low G',
        cover: 'img/banner/00001.jpg',
    },
    {
        id: '00075',
        name: 'Những vì tinh tú trong đôi mắt em (Soft Version)',
        path: 'audio/Những Vì Tinh Tú Trong Đôi Mắt Em.mp3',
        artist: 'HaiSam',
        cover: 'img/banner/00075.jpg',
    },
    {
        id: '00076',
        name: 'Name (feat. Tori Kelly)',
        path: 'audio/Justin Bieber - Name.mp3',
        artist: 'Justin Bieber, Tori Kelly',
        cover: 'img/banner/00076.jpg',
    },
    {
        id: '00077',
        name: 'Fashion Tán Gái',
        path: 'audio/FASHION TÁN GÁI.mp3',
        artist: 'Low G, Wren Evans',
        cover: 'img/banner/00077.jpg',
    },
    {
        id: '00002',
        name: 'Head In The Clouds',
        path: 'audio/Head In The Clouds _ Hayd.ogg',
        artist: 'Hayd',
        cover: 'img/banner/00002.jpg',
    },
    {
        id: '00011',
        name: 'EVERYTHING',
        path: 'audio/EVERYTHING -The Black Skirts.ogg',
        artist: 'The Black Skirts',
        cover: 'img/banner/00011.jpg',
    },
    {
        id: '00025',
        name: 'Bên Trái',
        path: 'audio/KIEN - BÊN TRÁI.mp3',
        artist: 'Kiên Trịnh',
        cover: 'img/banner/00025.jpg',
    },
    {
        id: '00017',
        name: 'Nhìn Những Mùa Thu Đi',
        path: 'audio/00017.aac',
        artist: 'My Anh',
        cover: 'img/banner/00017.jpg',
    },
    {
        id: '00054',
        name: "Not Thinkin' Bout You",
        path: "audio/Ruel - Not Thinkin' Bout You.mp3",
        artist: 'Ruel',
        cover: 'img/banner/00054.jpg',
    },
    {
        id: '00030',
        name: 'mot nguoi vi em (midnight)',
        path: 'audio/WEAN - mot nguoi vi em (midnight).mp3',
        artist: 'WEAN',
        cover: 'img/banner/00009.jpg',
    },
    {
        id: '00078',
        name: 'Apocalypse',
        path: 'audio/Apocalypse - Cigarettes After Sex.mp3',
        artist: 'Cigarettes After Sex',
        cover: 'img/banner/00078.jpg',
    },
    {
        id: '00008',
        name: 'Tay To',
        path: 'audio/Tay To _ Rapital, RPT MCK, RPT PhongKhin.ogg',
        artist: 'Rapital, RPT MCK, RPT PhongKhin',
        cover: 'img/banner/00008.jpg',
    },
    {
        id: '00005',
        name: 'Money Trees (Feat. Jay Rock)',
        path: 'audio/Money Trees (Feat. Jay Rock) _ Kendrick Lamar.ogg',
        artist: 'Kendrick Lamar, Jay Rock',
        cover: 'img/banner/00005.jpg',
    },
    
    {
        id: '00028',
        name: 'Shinunoga E-Wa',
        path: 'audio/Shinunoga E-Wa.mp3',
        artist: 'Fujii Kaze',
        cover: 'img/banner/00028.jpg',
    },
    {
        id: '00029',
        name: 'Bây Giờ Tháng Mấy',
        path: 'audio/00029.aac',
        artist: 'Nguyễn Thùy Linh',
        cover: 'img/banner/00029.jpg',
    },
    {
        id: '00015',
        name: 'Thôi Em Đừng Đi',
        path: 'audio/Thôi Em Đừng Đi - RPT MCK ( ft. Trung Trần ).mp3',
        artist: 'RPT MCK, Trung Trần',
        cover: 'img/banner/00015.jpg',
    },
    {
        id: '00031',
        name: 'Myself',
        path: 'audio/Post Malone - Myself.mp3',
        artist: 'Post Malone',
        cover: 'img/banner/00031.jpg',
    },
    {
        id: '00032',
        name: 'Kill Bill',
        path: 'audio/SZA - Kill Bill.mp3',
        artist: 'SZA',
        cover: 'img/banner/00032.jpg',
    },
    {
        id: '00033',
        name: 'Open Arms (feat. Travis Scott)',
        path: 'audio/SZA - Open Arms (Audio) ft. Travis Scott.mp3',
        artist: 'SZA, Travis Scott',
        cover: 'img/banner/00032.jpg',
    },
    {
        id: '00079',
        name: 'K.',
        path: 'audio/K. - Cigarettes After Sex.mp3',
        artist: 'Cigarettes After Sex',
        cover: 'img/banner/00079.jpg',
    },
    {
        id: '00055',
        name: "GROWING UP IS _____",
        path: "audio/Ruel - GROWING UP IS _____.mp3",
        artist: 'Ruel',
        cover: 'img/banner/00055.jpg',
    },
    {
        id: '00034',
        name: 'Happier Than Ever (ASTN cover)',
        path: 'audio/billie eillish - happier than ever (ASTN cover).mp3',
        artist: 'ASTN',
        cover: 'img/banner/00034.jpg',
    },
    {
        id: '00036',
        name: 'Sao Soi Đường Đêm',
        path: 'audio/Trung Trần - Sao Soi Đường Đêm ft. Jimmi Ngủyên.mp3',
        artist: 'Trung Trần, Trung Tâm Băng Đĩa Lậu Hải Ngoại, Jimmi Ngủyên',
        cover: 'img/banner/00036.jpg',
    },
    {
        id: '00056',
        name: 'ANGEL',
        path: 'audio/ANGEL.mp3',
        artist: 'keshi',
        cover: 'img/banner/00056.jpg',
    },
    {
        id: '00037',
        name: 'One More Shot',
        path: 'audio/CIL - One More Shot.mp3',
        artist: 'CIL',
        cover: 'img/banner/00037.jpg',
    },
    {
        id: '00038',
        name: 'Loving u is harder',
        path: 'audio/SEB - loving u is harder.mp3',
        artist: 'SEB',
        cover: 'img/banner/00038.jpg',
    },
    {
        id: '00039',
        name: 'Lếu Lều',
        path: 'audio/lếu lều -  michael hư đốn x jimmi ngủyên.mp3',
        artist: 'Trung Tâm Băng Đĩa Lậu Hải Ngoại',
        cover: 'img/banner/00039.jpg',
    },
    {
        id: '00040',
        name: "Still Don't Know My Name",
        path: "audio/Labrinth - Still Don't Know My Name.mp3",
        artist: 'Labrinth',
        cover: 'img/banner/00040.jpg',
    },
    {
        id: '00041',
        name: 'Show Me How',
        path: 'audio/Show Me How.mp3',
        artist: 'Men I Trust',
        cover: 'img/banner/00041.jpg',
    },
    {
        id: '00042',
        name: 'Hái Sao',
        path: 'audio/00042.m4a',
        artist: 'Pixel Neko, Thắng',
        cover: 'img/banner/00042.jpg',
    },
    {
        id: '00043',
        name: 'Low',
        path: 'audio/SZA - Low.mp3',
        artist: 'SZA',
        cover: 'img/banner/00032.jpg',
    },
    {
        id: '00044',
        name: 'Snooze',
        path: 'audio/SZA - Snooze.mp3',
        artist: 'SZA',
        cover: 'img/banner/00032.jpg',
    },
    {
        id: '00080',
        name: 'Sweet',
        path: 'audio/Sweet - Cigarettes After Sex.mp3',
        artist: 'Cigarettes After Sex',
        cover: 'img/banner/00080.jpg',
    },
    {
        id: '00045',
        name: 'listen up - Radio Edit',
        path: 'audio/SOLOMON - listen up (Radio Edit).mp3',
        artist: 'SOLOMON',
        cover: 'img/banner/00045.jpg',
    },
    {
        id: '00046',
        name: 'Call Me',
        path: 'audio/Call Me - Rangga Jones.mp3',
        artist: 'Rangga Jones',
        cover: 'img/banner/00046.jpg',
    },
    {
        id: '00058',
        name: 'Kiss Me More (feat. SZA)',
        path: 'audio/Doja Cat - Kiss Me More.mp3',
        artist: 'Doja Cat, SZA',
        cover: 'img/banner/00058.jpg',
    },
    {
        id: '00047',
        name: 'idontwannabeyouanymore',
        path: 'audio/Billie Eilish - idontwannabeyouanymore.mp3',
        artist: 'Billie Eilish',
        cover: 'img/banner/00047.jpg',
    },
    {
        id: '00048',
        name: 'nếu lúc đó',
        path: 'audio/tlinh - nếu lúc đó (ft. 2pillz).mp3',
        artist: 'tlinh, 2pillz',
        cover: 'img/banner/00048.jpg',
    },
    {
        id: '00049',
        name: 'LOVE. FEAT. ZACARI.',
        path: 'audio/LOVE ft. Zacari - Kendrick Lamar (DAMN).mp3',
        artist: 'Kendrick Lamar, Zacari',
        cover: 'img/banner/00049.jpg',
    },
    {
        id: '00069',
        name: "Shed a Light",
        path: 'audio/ROBIN SCHULZ & DAVID GUETTA & CHEAT CODES _ SHED A LIGHT.mp3',
        artist: 'Robin Schulz, David Guetta, Cheat Codes',
        cover: 'img/banner/00069.jpg',
    },
    {
        id: '00050',
        name: 'Endless Love',
        path: 'audio/ENDLESS LOVE - Lionel Ritchie duet w Diana Ross w lyrics.mp3',
        artist: 'Rionel Richie, Diana Ross',
        cover: 'img/banner/00050.jpg',
    },
    {
        id: '00051',
        name: 'Thinking Out Loud',
        path: 'audio/Ed Sheeran - Thinking out Loud.mp3',
        artist: 'Ed Sheeran',
        cover: 'img/banner/00051.jpg',
    },
    {
        id: '00052',
        name: "I Don't Care (with Justin Bieber)",
        path: "audio/Ed Sheeran & Justin Bieber - I Don't Care.mp3",
        artist: 'Ed Sheeran, Justin Bieber',
        cover: 'img/banner/00052.jpg',
    },
    {
        id: '00081',
        name: 'Cry',
        path: 'audio/Cry - Cigarettes After Sex.mp3',
        artist: 'Cigarettes After Sex',
        cover: 'img/banner/00081.jpg',
    },
    {
        id: '00053',
        name: "Face To Face",
        path: "audio/Ruel - Face To Face.mp3",
        artist: 'Ruel',
        cover: 'img/banner/00053.jpg',
    },
    {
        id: '00057',
        name: 'Say So',
        path: 'audio/Doja Cat - Say So.mp3',
        artist: 'Doja Cat',
        cover: 'img/banner/00057.jpg',
    },
    {
        id: '00059',
        name: 'god of the sunsets',
        path: 'audio/00059.aac',
        artist: 'SEB',
        cover: 'img/banner/00059.jpg',
    },
    {
        id: '00060',
        name: 'Last',
        path: 'audio/다운 (Dvwn) - 마지막 (Last).mp3',
        artist: 'Dvwn',
        cover: 'img/banner/00060.jpg',
    },
    {
        id: '00062',
        name: 'Champagne Shots',
        path: 'audio/Sainté - Champagne Shots.mp3',
        artist: 'Sainté',
        cover: 'img/banner/00062.jpg',
    },
    {
        id: '00063',
        name: 'Tell Em',
        path: 'audio/Cochise, $NOT - Tell Em.mp3',
        artist: 'Cochise, $NOT',
        cover: 'img/banner/00063.jpg',
    },
    {
        id: '00082',
        name: 'Heavenly',
        path: 'audio/Heavenly - Cigarettes After Sex.mp3',
        artist: 'Cigarettes After Sex',
        cover: 'img/banner/00082.jpg',
    },
    {
        id: '00083',
        name: 'Pistol',
        path: 'audio/Pistol - Cigarettes After Sex.mp3',
        artist: 'Cigarettes After Sex',
        cover: 'img/banner/00083.jpg',
    },
    {
        id: '00064',
        name: 'Honest',
        path: 'audio/rei brown - Honest.mp3',
        artist: 'rei brown',
        cover: 'img/banner/00064.jpg',
    },
    {
        id: '00065',
        name: "If I Ain't Got You - Acoustic",
        path: "audio/John Adams - If I Ain't Got You (Alicia Keys Acoustic Cover).mp3",
        artist: 'John Adams',
        cover: 'img/banner/00065.jpg',
    },
    {
        id: '00066',
        name: "Oceane (feat. Olivia Escuyos)",
        path: "audio/RINI - Oceane ft.mp3",
        artist: 'RINI, Olivia Escuyos',
        cover: 'img/banner/00066.jpg',
    },
    {
        id: '00067',
        name: "Honey",
        path: "audio/Johnny Balik - Honey.mp3",
        artist: 'Johnny Balik',
        cover: 'img/banner/00067.jpg',
    },
    {
        id: '00068',
        name: "Broke",
        path: "audio/Samm Henshaw - Broke.mp3",
        artist: 'Samm Henshaw',
        cover: 'img/banner/00068.jpg',
    },
    {
        id: '00070',
        name: "No Promises (feat. Demi Lovato)",
        path: "audio/Cheat Codes - No Promises.mp3",
        artist: 'Cheat Codes, Demi Lovato',
        cover: 'img/banner/00070.jpg',
    },
    {
        id: '00071',
        name: "Future",
        path: "audio/Future.mp3",
        artist: 'KIDO3008',
        cover: 'img/banner/00071.jpg',
    },
    {
        id: '00072',
        name: "Cherry Blossom",
        path: "audio/BOBBY Cherry Blossom.mp3",
        artist: 'BOBBY',
        cover: 'img/banner/00072.jpg',
    },
    {
        id: '00073',
        name: "Flower",
        path: "audio/Johnny Stimson - Flower.mp3",
        artist: 'Johnny Stimson',
        cover: 'img/banner/00073.jpg',
    },
    {
        id: '00074',
        name: "Violent Crimes",
        path: "audio/Kanye West - Violent Crimes.mp3",
        artist: 'Kanye West',
        cover: 'img/banner/00074.jpg',
    },
    {
        id: '00084',
        name: "Moonlight",
        path: "audio/Kali Uchis - Moonlight.mp3",
        artist: 'Kali Uchis',
        cover: 'img/banner/00084.jpg',
    },
    {
        id: '00087',
        name: "Sanctuary",
        path: "audio/Sanctuary.mp3",
        artist: 'Joji',
        cover: 'img/banner/00087.jpg',
    },
    {
        id: '00088',
        name: "Circles",
        path: "audio/Post Malone - Circles.mp3",
        artist: 'Post Malone',
        cover: 'img/banner/00088.jpg',
    },
    {
        id: '00089',
        name: "Get You (feat. Kali Uchis)",
        path: "audio/Get You (feat. Kali Uchis).mp3",
        artist: 'Daniel Caesar, Kali Uchis',
        cover: 'img/banner/00089.jpg',
    },
    {
        id: '10003',
        name: "100 Questions (feat. B Ray)",
        path: "audio/10003.aac",
        artist: 'V#, B Ray',
        cover: 'img/banner/10003.jpg',
    },
    {
        id: '10004',
        name: 'whatever happens, happens (feat. Saabirose)',
        path: 'audio/PAR SG - whatever happens, happens ft. Saabirose.mp3',
        artist: 'PAR SG, Saabirose',
        cover: 'img/banner/10004.jpg',
    },
    {
        id: '10005',
        name: 'instagram (feat. Vũ Thanh Vân)',
        path: 'audio/PAR SG - instagram ft. Vũ Thanh Vân.mp3',
        artist: 'PAR SG, Vũ Thanh Vân',
        cover: 'img/banner/10005.jpg',
    },
    {
        id: '10006',
        name: 'Đừng Nghe Máy',
        path: 'audio/Đừng Nghe Máy - SIVAN .mp3',
        artist: 'SIVAN',
        cover: 'img/banner/10006.jpg',
    },
    {
        id: '10007',
        name: 'Lý Do Nào Để Quay Lại Với Nhau',
        path: 'audio/PAR SG x New$oulZ - Ly Do Nao De Quay Lai Voi Nhau.mp3',
        artist: 'PAR SG, New$oulZ',
        cover: 'img/banner/10007.jpg',
    },
    {
        id: '10008',
        name: 'Mat Troi Cua Em',
        path: 'audio/PAR SG x THDC - Mat Troi Cua Em.mp3',
        artist: 'PAR SG, THDC',
        cover: 'img/banner/10008.jpg',
    },
    {
        id: '10009',
        name: 'Voicemail 語音郵件',
        path: 'audio/Han Kim - Voicemail 語音郵件.mp3',
        artist: 'Han Kim',
        cover: 'img/banner/10009.jpg',
    },
    {
        id: '10010',
        name: 'Lying to myself',
        path: 'audio/Dab - Lying to myself.mp3',
        artist: 'Dab, sy',
        cover: 'img/banner/10010.jpg',
    },
    {
        id: '10011',
        name: 'Có Hay Từ Bao Giờ?',
        path: 'audio/Có Hay Từ Bao Giờ_ - NIEE ft. HAST, KEI.mp3',
        artist: 'NIEE, HAST, KEI',
        cover: 'img/banner/10011.jpg',
    },
    {
        id: '10012',
        name: 'Có Em',
        path: 'audio/Có em - Madihu ft. Low G.mp3',
        artist: 'Mahidu, Low G',
        cover: 'img/banner/10012.jpg',
    },
    {
        id: '10013',
        name: "(Don't) Fall In Love (feat. Kim Nguyen Martian & Galaxyy)",
        path: "audio/PAR SG - (Don't) Fall In Love ft.mp3",
        artist: 'PAR SG, Galaxyy, Kim Nguyen Martian',
        cover: 'img/banner/10013.jpg',
    },
    {
        id: '10014',
        name: 'thế giới có nơi nào cho em',
        path: 'audio/sweet liquor - thế giới có nơi nào cho em.mp3',
        artist: 'Sweet Liquor',
        cover: 'img/banner/10014.jpg',
    },
    {
        id: '00157',
        name: "Mở Mắt",
        path: "audio/00157.aac",
        artist: 'Lil Wuyn, Đen',
        cover: 'img/banner/00157.jpg',
    },
    {
        id: '10015',
        name: 'NGTANOISE',
        path: 'audio/Han Kim - Voicemail 語音郵件.mp3',
        artist: 'VSOUL, MFREE, TUYEN VO',
        cover: 'img/banner/10015.jpg',
    },
    {
        id: '10016',
        name: 'Mai Về',
        path: 'audio/Mai về (Lyric) - Dfoxie37 x Myhai.mp3',
        artist: 'Dfoxie37, Myhai',
        cover: 'img/banner/10016.jpg',
    },
    {
        id: '10017',
        name: "XTC(Xích Thêm Chút)(Remix)",
        path: "audio/Xích Thêm Chút - XTC Remix _ RPT Groovie ft TLinh x RPT MCK (Prod. by fat_benn & RPT LT)_ RAPITALOVE.mp3",
        artist: 'Rapital, Groovie, Lã Thắng, tlinh, RPT MCK',
        cover: 'img/banner/10017.jpg',
    },
    {
        id: '10018',
        name: "Don't Côi",
        path: "audio/Don't Côi - RPT Orijinn x Ronboogz.mp3",
        artist: 'RPT Orijinn, Ronboogz',
        cover: 'img/banner/10018.jpg',
    },
    {
        id: '10019',
        name: "Ngủ sớm đi em",
        path: "audio/Ngủ sớm đi em - DucMinh ( Prod. by GC ).mp3",
        artist: 'DucMinh',
        cover: 'img/banner/10019.jpg',
    },
    {
        id: '10020',
        name: "anh không buồn như em nghĩ",
        path: "audio/anh không buồn như em nghĩ.mp3",
        artist: 'kis',
        cover: 'img/banner/10020.jpg',
    },
    {
        id: '10021',
        name: "Em Chưa Giấu Anh Điều Gì (CM1X Remix)",
        path: "audio/EM CHƯA GIẤU ANH ĐIỀU GÌ (CM1X REMIX) _ D.BLUE & ĐẠT G.mp3",
        artist: 'D.BLue, Đạt G',
        cover: 'img/banner/10021.jpg',
    },
    {
        id: '00158',
        name: "Go Crazy",
        path: "audio/00158.aac",
        artist: 'Chris Brown, Young Thug',
        cover: 'img/banner/00158.jpg',
    },
    {
        id: '10022',
        name: "Qua Ngày Mai",
        path: "audio/10022.aac",
        artist: 'Tiên Tiên',
        cover: 'img/banner/10022.jpg',
    },
    {
        id: '10023',
        name: "Chỉ Là Quá Khứ (Feat. Young Crizzbe)",
        path: "audio/Chỉ Là Quá Khứ _$eadreak ft young crizzbe.mp3",
        artist: '$eadreak, Young Crizzbe',
        cover: 'img/banner/10023.jpg',
    },
    {
        id: '10024',
        name: "3107 4 (Feat. Erik, Nâu)",
        path: "audio/W-n - 3107 4 x Erik ft Nâu (Official Music Video).mp3",
        artist: 'W/N, Erik, Nâu',
        cover: 'img/banner/10024.jpg',
    },
    {
        id: '10025',
        name: "Tôi Chỉ Muốn Là Người Duy Nhất Em Yêu",
        path: "audio/Tôi Chỉ Muốn Là Người Duy Nhất Em Yêu.mp3",
        artist: 'Linh',
        cover: 'img/banner/10025.jpg',
    },
    {
        id: '10026',
        name: "Đâu Ai Vì Nhau",
        path: "audio/10026.aac",
        artist: 'Khánh DaLa',
        cover: 'img/banner/10026.jpg',
    },
    {
        id: '10027',
        name: "Tình Yêu Chậm Trễ",
        path: "audio/Tình Yêu Chậm Trễ - Monstar (Slow Ver) by Khoi.mp3",
        artist: 'Khoi, GREY D',
        cover: 'img/banner/10027.jpg',
    },
    {
        id: '10028',
        name: "Trước Khi Em Tồn Tại (Piano Version)",
        path: "audio/Trước Khi Em Tồn Tại (Piano Version) - Thắng _ Việt Anh Cover.mp3",
        artist: 'Thắng, Việt Anh',
        cover: 'img/banner/10028.jpg',
    },
    {
        id: '00159',
        name: "Dusk Till Dawn (feat. Sia) - Radio Edit",
        path: "audio/00159.aac",
        artist: 'ZAYN, Sia',
        cover: 'img/banner/00159.jpg',
    },
    {
        id: '10030',
        name: "10. Finale 2 (Outro)",
        path: "audio/[DTT&TT] 10 .mp3",
        artist: 'B Ray',
        cover: 'img/banner/10030.jpg',
    },
    {
        id: '10031',
        name: "gói tình em rồi về",
        path: "audio/Phùng Khánh Linh - gói tình em rồi về.mp3",
        artist: 'Phùng Khánh Linh',
        cover: 'img/banner/10031.jpg',
    },
    {
        id: '10032',
        name: "yêu như chiến tranh (Feat. Jay Kem)",
        path: "audio/'Yêu như chiến tranh' - Bảo Uyên ft. Jay Kem.mp3",
        artist: 'Bảo Uyên, Jay Kem',
        cover: 'img/banner/10032.jpg',
    },
    {
        id: '10033',
        name: "Chiếc Thuyền Ngoài Xa",
        path: "audio/Chiếc thuyền ngoài xa - Minh Lý.mp3",
        artist: 'Minh Lý',
        cover: 'img/banner/10033.jpg',
    },
    {
        id: '10034',
        name: "Mashup by Wikin 25 Taos x Young H x Sol'Bass x Nah x B Ray x Chú 13 x Khói",
        path: "audio/Mashup by Wikin 25   Táo x Young H x Sol'Bass x Nah x B Ray x Chú 13 x Khói.mp3",
        artist: "Wikin 25 Táo, Young H, Sol'Bass, Nah, B Ray, Chú 13, Khói",
        cover: 'img/banner/10034.jpg',
    },
    {
        id: '10036',
        name: "Con Gái Rượu",
        path: "audio/B RAY x MASEW - CON GÁI RƯỢU.mp3",
        artist: 'B Ray, MASEW',
        cover: 'img/banner/10036.jpg',
    },
    {
        id: '10037',
        name: "Khi Em Lớn (Feat. Hoàng Dũng)",
        path: "audio/Khi Em Lớn - Orange x Hoàng Dũng.mp3",
        artist: 'Orange, Hoàng Dũng',
        cover: 'img/banner/10037.jpg',
    },
    {
        id: '10038',
        name: "Cao Ốc 20",
        path: "audio/Cao Ốc 20 _ B RAY x DatG.mp3",
        artist: 'B Ray, DatG',
        cover: 'img/banner/10038.jpg',
    },
    {
        id: '10039',
        name: "SAIGON SIMPLE LOVE (with Seth)",
        path: "audio/SAIGON SIMPLE LOVE (với Seth) - Nguyên (320 kbps).mp3",
        artist: 'Nguyên, Seth',
        cover: 'img/banner/10039.jpg',
    },
    {
        id: '10040',
        name: "ONLY",
        path: "audio/ONLY.mp3",
        artist: 'LeeHi',
        cover: 'img/banner/10040.jpg',
    },
    {
        id: '10041',
        name: "Ngủ Ngoan Em nhé",
        path: "audio/10041.aac",
        artist: 'GREY D',
        cover: 'img/banner/10041.jpg',
    },
    {
        id: '10042',
        name: "2 5 - Live Version",
        path: "audio/10042.m4a",
        artist: 'Táo',
        cover: 'img/banner/10042.jpg',
    },
    {
        id: '10043',
        name: "Anh Là Ai? (feat. Dick, DT & UMIE)",
        path: "audio/10043.m4a",
        artist: 'RAP VIỆT, Dick, DT, UMIE',
        cover: 'img/banner/10043.jpg',
    },
    {
        id: '10044',
        name: "Blue Tequila",
        path: "audio/10044.aac",
        artist: 'Táo',
        cover: 'img/banner/10044.jpg',
    },
    {
        id: '10045',
        name: "Vương",
        path: "audio/10045.aac",
        artist: 'RPT MCK',
        cover: 'img/banner/10045.jpg',
    },
    {
        id: '00090',
        name: "She's A 10 But...",
        path: "audio/ARTAN feat. Spencer Elmer - She's A 10 But....mp3",
        artist: 'ARTAN, Spencer Elmer',
        cover: 'img/banner/00090.jpg',
    },
    {
        id: '00091',
        name: "I Just Wanna Know",
        path: "audio/00091.mp3",
        artist: 'Wren Evans',
        cover: 'img/banner/00091.jpg',
    },
    {
        id: '00092',
        name: "Wrapped Around Your Finger",
        path: "audio/00092.mp3",
        artist: 'Post Malone',
        cover: 'img/banner/00092.jpg',
    },
    {
        id: '00093',
        name: "Candy Paint",
        path: "audio/00093.mp3",
        artist: 'Post Malone',
        cover: 'img/banner/00093.jpg',
    },
    {
        id: '00094',
        name: "Sunflower - Spider-Man: Into the Spider-Verse",
        path: "audio/00094.mp3",
        artist: 'Post Malone, Swae Lee',
        cover: 'img/banner/00094.jpg',
    },
    {
        id: '00095',
        name: "Chemical",
        path: "audio/00095.mp3",
        artist: 'Post Malone',
        cover: 'img/banner/00095.jpg',
    },
    {
        id: '00096',
        name: "After The Storm (feat. Tyler, The Creator & Bootsy Collins)",
        path: "audio/00096.mp3",
        artist: 'Kali Uchis, Tyler-The Creator, Bootsy Collins',
        cover: 'img/banner/00096.jpg',
    },
    {
        id: '00097',
        name: "Television / So Far So Good (voice memo)",
        path: "audio/00097.mp3",
        artist: 'Fran Vasilić',
        cover: 'img/banner/00097.jpg',
    },
    {
        id: '00098',
        name: "Anh Thấy (Interlude)",
        path: "audio/00098.mp3",
        artist: 'Wren Evans',
        cover: 'img/banner/00098.jpg',
    },
    {
        id: '00099',
        name: "At Least We Tried",
        path: "audio/00099.mp3",
        artist: 'Giveon',
        cover: 'img/banner/00099.jpg',
    },
    {
        id: '00100',
        name: "better for you",
        path: "audio/00100.mp3",
        artist: 'siopaolo',
        cover: 'img/banner/00100.jpg',
    },
    {
        id: '00101',
        name: "đôi mình",
        path: "audio/00101.mp3",
        artist: 'Chuột Sấm Sét',
        cover: 'img/banner/00101.jpg',
    },
    {
        id: '00102',
        name: "Violet",
        path: "audio/00102.mp3",
        artist: 'Connor Price, Killa',
        cover: 'img/banner/00102.jpg',
    },
    {
        id: '00103',
        name: "La Cienega",
        path: "audio/00103.mp3",
        artist: '88rising, Joji, NIKI',
        cover: 'img/banner/00086.jpg',
    },
    {
        id: '00104',
        name: "What Do You Mean?",
        path: "audio/00104.mp3",
        artist: 'Justin Bieber',
        cover: 'img/banner/00104.jpg',
    },
    {
        id: '00105',
        name: "Chỉ Một Đêm Nữa Thôi",
        path: "audio/00105.mp3",
        artist: 'RPT MCK, tlinh',
        cover: 'img/banner/00015.jpg',
    },
    {
        id: '00106',
        name: "bando - sped up + reverb",
        path: "audio/00106.mp3",
        artist: 'bbygirl',
        cover: 'img/banner/00106.jpg',
    },
    {
        id: '00107',
        name: "I Like You(A Happier Song)(with Doja Cat)",
        path: "audio/00107.mp3",
        artist: 'Post Malone, Doja Cat',
        cover: 'img/banner/00092.jpg',
    },
    {
        id: '00108',
        name: "Ballroom Extravaganza",
        path: "audio/00108.mp3",
        artist: 'DPR IAN',
        cover: 'img/banner/00108.jpg',
    },
    {
        id: '00109',
        name: "Reeves (feat. Manbo & HIEUTHUHAI)",
        path: "audio/00109.mp3",
        artist: 'HURRYKNG, HIEUTHUHAI, MANBO',
        cover: 'img/banner/00109.jpg',
    },
    {
        id: '00110',
        name: "Save Your Tears",
        path: "audio/00110.mp3",
        artist: 'The Weeknd',
        cover: 'img/banner/00110.jpg',
    },
    {
        id: '00111',
        name: "Trao",
        path: "audio/00111.mp3",
        artist: 'Wren Evans',
        cover: 'img/banner/00098.jpg',
    },
    {
        id: '00112',
        name: "5 STAR",
        path: "audio/00112.mp3",
        artist: 'CL',
        cover: 'img/banner/00112.jpg',
    },
    {
        id: '00156',
        name: "The Archer",
        path: "audio/00156.aac",
        artist: 'Taylor Swift',
        cover: 'img/banner/00156.jpg',
    },
    {
        id: '00113',
        name: "Màu Đỏ (Interlude)",
        path: "audio/00113.mp3",
        artist: 'Wren Evans',
        cover: 'img/banner/00098.jpg',
    },
    {
        id: '00114',
        name: "Mourning",
        path: "audio/00114.mp3",
        artist: 'Post Malone',
        cover: 'img/banner/00114.jpg',
    },
    {
        id: '00115',
        name: "I Cannot Be(A Sadder Song)(with Gunna)",
        path: "audio/00115.mp3",
        artist: 'Post Malone, Gunna',
        cover: 'img/banner/00092.jpg',
    },
    {
        id: '00116',
        name: "Tommy Lee (feat. Post Malone)",
        path: "audio/00116.mp3",
        artist: 'Tyla Yaweh, Post Malone',
        cover: 'img/banner/00116.jpg',
    },
    {
        id: '00117',
        name: "Stuck with U (with Justin Bieber)",
        path: "audio/00117.mp3",
        artist: 'Ariana Grande, Justin Bieber',
        cover: 'img/banner/00117.jpg',
    },
    {
        id: '00118',
        name: "Gặp May",
        path: "audio/00118.mp3",
        artist: 'Wren Evans',
        cover: 'img/banner/00118.jpg',
    },
    {
        id: '00119',
        name: "BADBYE",
        path: "audio/00119.mp3",
        artist: 'WEAN',
        cover: 'img/banner/00119.jpg',
    },
    {
        id: '00120',
        name: "A Lovesong for Whoever",
        path: "audio/00120.mp3",
        artist: 'Fran Vasilić',
        cover: 'img/banner/00120.jpg',
    },
    {
        id: '00121',
        name: "Mấy Khi",
        path: "audio/00121.mp3",
        artist: 'Ngọt',
        cover: 'img/banner/00121.jpg',
    },
    {
        id: '00122',
        name: "Mấy Khi",
        path: "audio/00122.mp3",
        artist: 'Wren Evans',
        cover: 'img/banner/00098.jpg',
    },
    {
        id: '00123',
        name: "Paris in the Rain",
        path: "audio/00123.mp3",
        artist: 'Lauv',
        cover: 'img/banner/00123.jpg',
    },
    {
        id: '00124',
        name: "Younger",
        path: "audio/00124.mp3",
        artist: 'Ruel',
        cover: 'img/banner/00124.jpg',
    },
    {
        id: '00125',
        name: "Japanese Pancakes",
        path: "audio/00125.mp3",
        artist: 'Fran Vasilić',
        cover: 'img/banner/00125.jpg',
    },
    {
        id: '00126',
        name: "Baby Powder",
        path: "audio/00126.mp3",
        artist: 'Jenevieve',
        cover: 'img/banner/00126.jpg',
    },
    {
        id: '00127',
        name: "LIMBO",
        path: "audio/00127.mp3",
        artist: 'keshi',
        cover: 'img/banner/00056.jpg',
    },
    {
        id: '00128',
        name: "Hột Xoàn (feat. HURRYKNG & Negav)",
        path: "audio/00128.mp3",
        artist: 'Cam, MinhLai, Anh Phan, HURRYKNG, Negav',
        cover: 'img/banner/00128.jpg',
    },
    {
        id: '00129',
        name: "ROCKSTAR (feat. Roddy Ricch)",
        path: "audio/00125.mp3",
        artist: 'DaBaby, Roddy Ricch',
        cover: 'img/banner/00129.jpg',
    },
    {
        id: '00130',
        name: "Watch This - ARIZONATEARS Pluggnb Remix",
        path: "audio/00130.mp3",
        artist: 'Lil Uzi Vert, sped up nightcore, ARIZONATEARS',
        cover: 'img/banner/00130.jpg',
    },
    {
        id: '00155',
        name: "my tears ricochet",
        path: "audio/00155.aac",
        artist: 'Taylor Swift',
        cover: 'img/banner/00155.jpg',
    },
    {
        id: '00131',
        name: "Hiểu Thứ Tha",
        path: "audio/00131.mp3",
        artist: 'Trung Tâm Băng Đĩa Lậu Hải Ngoại',
        cover: 'img/banner/00131.jpg',
    },
    {
        id: '00132',
        name: "UNDERSTAND",
        path: "audio/00132.mp3",
        artist: 'keshi',
        cover: 'img/banner/00056.jpg',
    },
    {
        id: '00133',
        name: "In Your Eyes",
        path: "audio/00133.mp3",
        artist: 'The Weeknd',
        cover: 'img/banner/00110.jpg',
    },
    {
        id: '00134',
        name: "Steal The Show",
        path: "audio/00134.aac",
        artist: 'Lauv',
        cover: 'img/banner/00134.jpg',
    },
    {
        id: '00135',
        name: "Attention",
        path: "audio/00135.mp3",
        artist: 'NewJeans',
        cover: 'img/banner/00135.jpg',
    },
    {
        id: '00136',
        name: "Super Shy",
        path: "audio/00136.mp3",
        artist: 'NewJeans',
        cover: 'img/banner/00136.jpg',
    },
    {
        id: '00154',
        name: "long story short",
        path: "audio/00154.aac",
        artist: 'Taylor Swift',
        cover: 'img/banner/00154.jpg',
    },
    {
        id: '00137',
        name: "Forget Me Now",
        path: "audio/00137.mp3",
        artist: 'Fishy, Trí Dũng',
        cover: 'img/banner/00137.jpg',
    },
    {
        id: '00138',
        name: "IT'S YOU (feat. keshi)",
        path: "audio/00138.mp3",
        artist: 'MAX, keshi',
        cover: 'img/banner/00138.jpg',
    },
    {
        id: '00139',
        name: "Cô Nàng Khác Người",
        path: "audio/00139.mp3",
        artist: 'Pixel Neko, RPT MCK, Wxrdie',
        cover: 'img/banner/00139.jpg',
    },
    {
        id: '00140',
        name: "Christmas Kids",
        path: "audio/00140.mp3",
        artist: 'Roar',
        cover: 'img/banner/00140.jpg',
    },
    {
        id: '00141',
        name: "Vì Sao Thế Vì Sạo Lòng",
        path: "audio/00141.mp3",
        artist: 'Trung Tâm Băng Đĩa Lậu Hải Ngoại',
        cover: 'img/banner/00141.jpg',
    },
    {
        id: '00142',
        name: "The Great Gig in the Sky",
        path: "audio/00142.mp3",
        artist: 'Pink Floyd',
        cover: 'img/banner/00142.jpg',
    },
    {
        id: '00151',
        name: "Butterflies",
        path: "audio/00151.aac",
        artist: 'Abe Parker',
        cover: 'img/banner/00151.jpg',
    },
    {
        id: '00143',
        name: "Take Off Everything, Pt. 2",
        path: "audio/00143.mp3",
        artist: 'Lønelo, DWELLS',
        cover: 'img/banner/00143.jpg',
    },
    {
        id: '00152',
        name: "Nothing New (feat. Phoebe Bridgers)",
        path: "audio/00152.aac",
        artist: 'Taylor Swift',
        cover: 'img/banner/00152.jpg',
    },
    {
        id: '00153',
        name: "I Almost Do",
        path: "audio/00153.aac",
        artist: 'Taylor Swift',
        cover: 'img/banner/00152.jpg',
    },
    {
        id: '00144',
        name: "Beautiful (feat. Camila Cabello)",
        path: "audio/00144.mp3",
        artist: 'Bazzi, Camila Cabello',
        cover: 'img/banner/00144.jpg',
    },
    {
        id: '00145',
        name: "ASAP",
        path: "audio/00145.mp3",
        artist: 'NewJeans',
        cover: 'img/banner/00136.jpg',
    },
    {
        id: '00146',
        name: "golden hour - Fujii Kaze Remix",
        path: "audio/00146.mp3",
        artist: 'JVKE, Fujii Kaze',
        cover: 'img/banner/00146.jpg',
    },
    {
        id: '00147',
        name: "Glue Song (feat. Clairo)",
        path: "audio/00147.mp3",
        artist: 'beabadoobee, Clairo',
        cover: 'img/banner/00147.jpg',
    },
    {
        id: '00148',
        name: "Dangerously",
        path: "audio/00148.m4a",
        artist: 'Charlie Puth',
        cover: 'img/banner/00148.jpg',
    },
    {
        id: '00149',
        name: "Can't Get Over You (Joji ft. Clams Casino) (kyuuwaii Cover)",
        path: "audio/00149.aac",
        artist: 'kyuuwaii',
        cover: 'img/banner/00149.jpg',
    },
    {
        id: '00150',
        name: "Numb Little Bug",
        path: "audio/00150.aac",
        artist: 'Em Beihold',
        cover: 'img/banner/00150.jpg',
    },
    {
        id: '00160',
        name: "The Greatest Show",
        path: "audio/00160.aac",
        artist: 'Hugh Jackman, Keala Settle, Zac Efron, Zendaya, The Greatest Showman Ensemble',
        cover: 'img/custom_cover/10001.jpg'
    },
    {
        id: '00161',
        name: "A Million Dreams",
        path: "audio/00161.aac",
        artist: 'Ziv Zaifman, Hugh Jackman, Michelle Williams',
        cover: 'img/custom_cover/10001.jpg'
    },
    {
        id: '00162',
        name: "A Million Dreams (Reprise)",
        path: "audio/00162.aac",
        artist: 'Hugh Jackman, Austyn Johnson, Cameron Seely',
        cover: 'img/custom_cover/10001.jpg'
    },
    {
        id: '00163',
        name: "Come Alive",
        path: "audio/00163.aac",
        artist: 'Hugh Jackman, Keala Settle, Daniel Everidge, Zendaya, The Greatest Showman Ensemble',
        cover: 'img/custom_cover/10001.jpg'
    },
    {
        id: '00164',
        name: "The Other Side",
        path: "audio/00164.aac",
        artist: 'Hugh Jackman, Zac Efron',
        cover: 'img/custom_cover/10001.jpg'
    },
    {
        id: '00165',
        name: "Never Enough",
        path: "audio/00165.aac",
        artist: 'Loren Alllred',
        cover: 'img/custom_cover/10001.jpg'
    },
    {
        id: '00166',
        name: "This Is Me",
        path: "audio/00166.aac",
        artist: 'Keala Settle, The Greatest Showman Ensemble',
        cover: 'img/custom_cover/10001.jpg'
    },
    {
        id: '00167',
        name: "Rewrite The Stars",
        path: "audio/00167.aac",
        artist: 'Zac Efron, Zendaya',
        cover: 'img/custom_cover/10001.jpg'
    },
    {
        id: '00168',
        name: "Tightrope",
        path: "audio/00168.aac",
        artist: 'Michelle Williams',
        cover: 'img/custom_cover/10001.jpg'
    },
    {
        id: '00169',
        name: "Never Enough (Reprise)",
        path: "audio/00169.aac",
        artist: 'Lorren Allred',
        cover: 'img/custom_cover/10001.jpg'
    },
    {
        id: '00170',
        name: "From Now On",
        path: "audio/00170.aac",
        artist: 'Hugh Jackman, The Greatest Showman Ensemble',
        cover: 'img/custom_cover/10001.jpg'
    }
]
