let songs = [
    {
        id: '00013',
        name: 'Die For You',
        path: 'audio/Joji - Die For You.mp3',
        artist: 'Joji',
        cover: 'img/banner/00013.jpg',
    },
    {
        id: '00035',
        name: 'golden hour - Ruel Remix',
        path: 'audio/JVKE - golden hour (Ruel Remix) .mp3',
        artist: 'JVKE, Ruel',
        cover: 'img/banner/00035.jpg',
    },
    {
        id: '00009',
        name: 'MOT NGUOI VI EM',
        path: 'audio/mot nguoi vi em (midnight) _ WEAN.ogg',
        artist: 'WEAN',
        cover: 'img/banner/00009.jpg',
    },
    {
        id: '00012',
        name: 'Matsuri',
        path: 'audio/Fujii Kaze -  Matsuri.ogg',
        artist: 'Fujii Kaze',
        cover: 'img/banner/00012.jpg',
    },
    {
        id: '00014',
        name: 'Die For You (with Ariana Grande) - Remix',
        path: 'audio/The Weeknd Ariana Grande - Die For You.mp3',
        artist: 'The Weeknd, Ariana Grande',
        cover: 'img/banner/00014.jpg',
    },
    {
        id: '00026',
        name: 'Kaerou',
        path: 'audio/Fujii Kaze - Kaerou.mp3',
        artist: 'Fujii Kaze',
        cover: 'img/banner/00026.jpg',
    },
    {
        id: '00021',
        name: 'Baby Why',
        path: 'audio/Sarah Cothran - Baby Why.mp3',
        artist: 'Sarah Cothran',
        cover: 'img/banner/00021.jpg',
    },
    {
        id: '00022',
        name: 'Chạy Ngay Đi',
        path: 'audio/CHẠY NGAY ĐI _ RUN NOW _ SƠN TÙNG M-TP.mp3',
        artist: 'Sơn Tùng M-TP, Onionn.',
        cover: 'img/banner/00022.jpg',
    },
    {
        id: '00003',
        name: 'Cắt kéo trên Lênin',
        path: 'audio/Cắt kéo trên Lênin _ Low G.ogg',
        artist: 'Low G',
        cover: 'img/banner/00003.jpg',
    },
    {
        id: '00004',
        name: 'Peaches (feat. Daniel Caesar & Giveon)',
        path: 'audio/Peaches (ft. Daniel Caesar, Giveon) _ Justin Bieber.ogg',
        artist: 'Justin Bieber, Daniel Caesar, Giveon',
        cover: 'img/banner/00004.jpg',
    },
    {
        id: '00016',
        name: 'Chìm Sâu',
        path: 'audio/Chìm Sâu - RPT MCK ( ft. Trung Trần ).mp3',
        artist: 'RPT MCK, Trung Trần',
        cover: 'img/banner/00016.jpg',
    },
    {
        id: '00006',
        name: 'Hard Feelings',
        path: 'audio/Hard Feelings _ Lorde.ogg',
        artist: 'Lorde',
        cover: 'img/banner/00006.jpg',
    },
    {
        id: '00010',
        name: 'magnolia',
        path: 'audio/magnolia _ keshi.ogg',
        artist: 'keshi',
        cover: 'img/banner/00010.jpg',
    },
    {
        id: '00027',
        name: 'YASASHISA',
        path: 'audio/Fujii Kaze - YASASHISA.mp3',
        artist: 'Fujii Kaze',
        cover: 'img/banner/00027.jpg',
    },
    {
        id: '00018',
        name: 'YOUR SMILE',
        path: 'audio/Obito ft. hnhngan live YOUR SMILE - Emma x Seachains x Obito.mp3',
        artist: 'Emma, Seachains, Obito, hnhngan',
        cover: 'img/banner/00018.jpg',
    },
    {
        id: '00061',
        name: 'Close To The Edge',
        path: 'audio/Close To The Edge by Fulton Lee.mp3',
        artist: 'Fulton Lee',
        cover: 'img/banner/00061.jpg',
    },
    {
        id: '00007',
        name: 'ガランド (Garando)',
        path: 'audio/ガランド _ NORISTRY.ogg',
        artist: 'NORISTRY',
        cover: 'img/banner/00007.jpg',
    },
    {
        id: '00023',
        name: 'CHẠY NGAY ĐI - Onionn Remixx',
        path: 'audio/CHẠY NGAY ĐI (ONIONN REMIX)_ RUN NOW (ONIONN REMIX) _ SƠN TÙNG M-TP.mp3',
        artist: 'Sơn Tùng M-TP, Onionn.',
        cover: 'img/banner/00023.jpg',
    },
    {
        id: '00024',
        name: 'Kirari',
        path: 'audio/Fujii Kaze _Kirari.mp3',
        artist: 'Fujii Kaze',
        cover: 'img/banner/00024.jpg',
    },
    {
        id: '00000',
        name: '踊り子 (Odoriko)',
        path: 'audio/踊り子 - Vaundy.mp3',
        artist: 'Vaundy',
        cover: 'img/banner/00000.jpg',
    },
    {
        id: '00019',
        name: 'Anh Đã Ổn Hơn',
        path: 'audio/Anh Đã Ổn Hơn - RPT MCK.mp3',
        artist: 'RPT MCK',
        cover: 'img/banner/00015.jpg',
    },
    {
        id: '00020',
        name: 'Forever (feat. Post Malone & Clever)',
        path: 'audio/Justin Bieber - Forever (feat. Post Malone Clever).mp3',
        artist: 'Justin Bieber, Post Malone, Clever',
        cover: 'img/banner/00020.jpg',
    },
    {
        id: '00001',
        name: 'Không Thích',
        path: 'audio/Không Thích _ Low G.mp3',
        artist: 'Low G',
        cover: 'img/banner/00001.jpg',
    },
    {
        id: '00002',
        name: 'Head In The Clouds',
        path: 'audio/Head In The Clouds _ Hayd.ogg',
        artist: 'Hayd',
        cover: 'img/banner/00002.jpg',
    },
    {
        id: '00011',
        name: 'EVERYTHING',
        path: 'audio/EVERYTHING -The Black Skirts.ogg',
        artist: 'The Black Skirts',
        cover: 'img/banner/00011.jpg',
    },
    {
        id: '00025',
        name: 'Bên Trái',
        path: 'audio/KIEN - BÊN TRÁI.mp3',
        artist: 'Kiên Trịnh',
        cover: 'img/banner/00025.jpg',
    },
    {
        id: '00017',
        name: 'Nhìn Những Mùa Thu Đi',
        path: 'audio/My Anh - nhìn những mùa thu đi.mp3',
        artist: 'My Anh',
        cover: 'img/banner/00017.jpg',
    },
    {
        id: '00054',
        name: "Not Thinkin' Bout You",
        path: "audio/Ruel - Not Thinkin' Bout You.mp3",
        artist: 'Ruel',
        cover: 'img/banner/00054.jpg',
    },
    {
        id: '00030',
        name: 'mot nguoi vi em (midnight)',
        path: 'audio/WEAN - mot nguoi vi em (midnight).mp3',
        artist: 'WEAN',
        cover: 'img/banner/00009.jpg',
    },
    {
        id: '00008',
        name: 'Tay To',
        path: 'audio/Tay To _ Rapital, RPT MCK, RPT PhongKhin.ogg',
        artist: 'Rapital, RPT MCK, RPT PhongKhin',
        cover: 'img/banner/00008.jpg',
    },
    {
        id: '00005',
        name: 'Money Trees (Feat. Jay Rock)',
        path: 'audio/Money Trees (Feat. Jay Rock) _ Kendrick Lamar.ogg',
        artist: 'Kendrick Lamar, Jay Rock',
        cover: 'img/banner/00005.jpg',
    },
    
    {
        id: '00028',
        name: 'Shinunoga E-Wa',
        path: 'audio/Shinunoga E-Wa.mp3',
        artist: 'Fujii Kaze',
        cover: 'img/banner/00028.jpg',
    },
    {
        id: '00029',
        name: 'Bây Giờ Tháng Mấy',
        path: 'audio/BÂY GIỜ THÁNG MẤY.mp3',
        artist: 'Nguyễn Thùy Linh',
        cover: 'img/banner/00029.jpg',
    },
    {
        id: '00015',
        name: 'Thôi Em Đừng Đi',
        path: 'audio/Thôi Em Đừng Đi - RPT MCK ( ft. Trung Trần ).mp3',
        artist: 'RPT MCK, Trung Trần',
        cover: 'img/banner/00015.jpg',
    },
    {
        id: '00031',
        name: 'Myself',
        path: 'audio/Post Malone - Myself.mp3',
        artist: 'Post Malone',
        cover: 'img/banner/00031.jpg',
    },
    {
        id: '00032',
        name: 'Kill Bill',
        path: 'audio/SZA - Kill Bill.mp3',
        artist: 'SZA',
        cover: 'img/banner/00032.jpg',
    },
    {
        id: '00033',
        name: 'Open Arms (feat. Travis Scott)',
        path: 'audio/SZA - Open Arms (Audio) ft. Travis Scott.mp3',
        artist: 'SZA, Travis Scott',
        cover: 'img/banner/00032.jpg',
    },
    {
        id: '00055',
        name: "GROWING UP IS _____",
        path: "audio/Ruel - GROWING UP IS _____.mp3",
        artist: 'Ruel',
        cover: 'img/banner/00055.jpg',
    },
    {
        id: '00034',
        name: 'Happier Than Ever (ASTN cover)',
        path: 'audio/billie eillish - happier than ever (ASTN cover).mp3',
        artist: 'ASTN',
        cover: 'img/banner/00034.jpg',
    },
    {
        id: '00036',
        name: 'Sao Soi Đường Đêm',
        path: 'audio/Trung Trần - Sao Soi Đường Đêm ft. Jimmi Ngủyên.mp3',
        artist: 'Trung Trần, Trung Tâm Băng Đĩa Lậu Hải Ngoại, Jimmi Ngủyên',
        cover: 'img/banner/00036.jpg',
    },
    {
        id: '00056',
        name: 'ANGEL',
        path: 'audio/ANGEL.mp3',
        artist: 'keshi',
        cover: 'img/banner/00056.jpg',
    },
    {
        id: '00037',
        name: 'One More Shot',
        path: 'audio/CIL - One More Shot.mp3',
        artist: 'CIL',
        cover: 'img/banner/00037.jpg',
    },
    {
        id: '00038',
        name: 'Loving u is harder',
        path: 'audio/SEB - loving u is harder.mp3',
        artist: 'SEB',
        cover: 'img/banner/00038.jpg',
    },
    {
        id: '00039',
        name: 'Lếu Lều',
        path: 'audio/lếu lều -  michael hư đốn x jimmi ngủyên.mp3',
        artist: 'Trung Tâm Băng Đĩa Lậu Hải Ngoại',
        cover: 'img/banner/00039.jpg',
    },
    {
        id: '00040',
        name: "Still Don't Know My Name",
        path: "audio/Labrinth - Still Don't Know My Name.mp3",
        artist: 'Labrinth',
        cover: 'img/banner/00040.jpg',
    },
    {
        id: '00041',
        name: 'Show Me How',
        path: 'audio/Show Me How.mp3',
        artist: 'Men I Trust',
        cover: 'img/banner/00041.jpg',
    },
    {
        id: '00042',
        name: 'Hái Sao',
        path: 'audio/HÁI SAO.mp3',
        artist: 'Pixel Neko, Thắng',
        cover: 'img/banner/00042.jpg',
    },
    {
        id: '00043',
        name: 'Low',
        path: 'audio/SZA - Low.mp3',
        artist: 'SZA',
        cover: 'img/banner/00032.jpg',
    },
    {
        id: '00044',
        name: 'Snooze',
        path: 'audio/SZA - Snooze.mp3',
        artist: 'SZA',
        cover: 'img/banner/00032.jpg',
    },
    {
        id: '00045',
        name: 'listen up - Radio Edit',
        path: 'audio/SOLOMON - listen up (Radio Edit).mp3',
        artist: 'SOLOMON',
        cover: 'img/banner/00045.jpg',
    },
    {
        id: '00046',
        name: 'Call Me',
        path: 'audio/Call Me - Rangga Jones.mp3',
        artist: 'Rangga Jones',
        cover: 'img/banner/00046.jpg',
    },
    {
        id: '00058',
        name: 'Kiss Me More (feat. SZA)',
        path: 'audio/Doja Cat - Kiss Me More.mp3',
        artist: 'Doja Cat, SZA',
        cover: 'img/banner/00058.jpg',
    },
    {
        id: '00047',
        name: 'idontwannabeyouanymore',
        path: 'audio/Billie Eilish - idontwannabeyouanymore.mp3',
        artist: 'Billie Eilish',
        cover: 'img/banner/00047.jpg',
    },
    {
        id: '00048',
        name: 'nếu lúc đó',
        path: 'audio/tlinh - nếu lúc đó (ft. 2pillz).mp3',
        artist: 'tlinh, 2pillz',
        cover: 'img/banner/00048.jpg',
    },
    {
        id: '00049',
        name: 'LOVE. FEAT. ZACARI.',
        path: 'audio/LOVE ft. Zacari - Kendrick Lamar (DAMN).mp3',
        artist: 'Kendrick Lamar, Zacari',
        cover: 'img/banner/00049.jpg',
    },
    {
        id: '00050',
        name: 'Endless Love',
        path: 'audio/ENDLESS LOVE - Lionel Ritchie duet w Diana Ross w lyrics.mp3',
        artist: 'Rionel Richie, Diana Ross',
        cover: 'img/banner/00050.jpg',
    },
    {
        id: '00051',
        name: 'Thinking Out Loud',
        path: 'audio/Ed Sheeran - Thinking out Loud.mp3',
        artist: 'Ed Sheeran',
        cover: 'img/banner/00051.jpg',
    },
    {
        id: '00052',
        name: "I Don't Care (with Justin Bieber)",
        path: "audio/Ed Sheeran & Justin Bieber - I Don't Care.mp3",
        artist: 'Ed Sheeran, Justin Bieber',
        cover: 'img/banner/00052.jpg',
    },
    {
        id: '00053',
        name: "Face To Face",
        path: "audio/Ruel - Face To Face.mp3",
        artist: 'Ruel',
        cover: 'img/banner/00053.jpg',
    },
    {
        id: '00057',
        name: 'Say So',
        path: 'audio/Doja Cat - Say So.mp3',
        artist: 'Doja Cat',
        cover: 'img/banner/00057.jpg',
    },
    {
        id: '00059',
        name: 'god of the sunsets',
        path: 'audio/SEB - god of the sunsets.mp3',
        artist: 'SEB',
        cover: 'img/banner/00059.jpg',
    },
    {
        id: '00060',
        name: 'Last',
        path: 'audio/다운 (Dvwn) - 마지막 (Last).mp3',
        artist: 'Dvwn',
        cover: 'img/banner/00060.jpg',
    },
    {
        id: '00062',
        name: 'Champagne Shots',
        path: 'audio/Sainté - Champagne Shots.mp3',
        artist: 'Sainté',
        cover: 'img/banner/00062.jpg',
    },
    {
        id: '00063',
        name: 'Tell Em',
        path: 'audio/Cochise, $NOT - Tell Em.mp3',
        artist: 'Cochise, $NOT',
        cover: 'img/banner/00063.jpg',
    },
    {
        id: '00064',
        name: 'Honest',
        path: 'audio/rei brown - Honest.mp3',
        artist: 'rei brown',
        cover: 'img/banner/00064.jpg',
    },
    {
        id: '00065',
        name: "If I Ain't Got You - Acoustic",
        path: "audio/John Adams - If I Ain't Got You (Alicia Keys Acoustic Cover).mp3",
        artist: 'John Adams',
        cover: 'img/banner/00065.jpg',
    },
    {
        id: '00066',
        name: "Oceane (feat. Olivia Escuyos)",
        path: "audio/RINI - Oceane ft.mp3",
        artist: 'RINI, Olivia Escuyos',
        cover: 'img/banner/00066.jpg',
    }
]
